<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="6" hostname="NTQ-PC" name="Tests.Login" tests="7" failures="0" timestamp="06 Oct 2017 09:53:57 GMT" time="39.984" errors="1">
  <testcase name="LoginSuccess" time="0.000" classname="Tests.Login">
    <skipped/>
  </testcase> <!-- LoginSuccess -->
  <testcase name="Unexisted_acc" time="0.000" classname="Tests.Login">
    <skipped/>
  </testcase> <!-- Unexisted_acc -->
  <testcase name="Blank_pw" time="0.000" classname="Tests.Login">
    <skipped/>
  </testcase> <!-- Blank_pw -->
  <testcase name="Blank_acc_pw" time="0.000" classname="Tests.Login">
    <skipped/>
  </testcase> <!-- Blank_acc_pw -->
  <testcase name="BeforeMethod" time="39.984" classname="Tests.Login">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at Pages.HomePage.account(HomePage.java:28)
	at Tests.Login.BeforeMethod(Login.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:523)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:224)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:599)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
    </error>
  </testcase> <!-- BeforeMethod -->
  <testcase name="Invalid_pw" time="0.000" classname="Tests.Login">
    <skipped/>
  </testcase> <!-- Invalid_pw -->
  <testcase name="Blank_acc" time="0.000" classname="Tests.Login">
    <skipped/>
  </testcase> <!-- Blank_acc -->
</testsuite> <!-- Tests.Login -->
